name: 🚀 Deploy website on push
on:
  push:
    branches: [ main ]
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📚 Prepare bib file
      run: |
        npm install
        sudo apt install xsltproc libxml2-utils bibutils bibtool -y
        mkdir lattes
        cd lattes
        git clone https://github.com/urbcomp-lab/SLattes.git
        cd SLattes
        xsltproc lattes2mods.xsl ../../curriculo.xml > curriculo.mods
        xml2bib -b -w curriculo.mods > curriculo.bib
        cp curriculo.bib ../../publications.bib
        cd ../../
        node bibToJSON.js publications.bib > publications.json

    - uses: "shivammathur/setup-php@v2"
      with:
        php-version: "8.1"
        extensions: mbstring, zip, intl, xml, curl, gd, exif, dom, fileinfo, json, pdo,tokenizer, xmlwriter, xmlreader, xsl, zip, ftp, imap, ldap, sockets, imagick, mcrypt, memcached, mongodb, redis, ssh2, tidy, yaml, opcache, intl, bcmath, calendar, gettext, gmp, iconv, pcntl, pdo_dblib, pdo_firebird, pdo_odbc, pdo_pgsql, pdo_sqlsrv, pgsql, pspell, recode, snmp, soap, sodium, sqlite, sysvmsg, sysvsem, sysvshm, wddx, xdebug, xmlrpc, xsl, zend_test, apcu, ast, ds, ev, event, inotify, lzf, mailparse, memcache, msgpack, oauth, propro, raphf, rdkafka, redis, ssh2, stomp, timezonedb, uopz, uuid, xdebug, xhprof, yaml, yar, zendopcache, zmq, amqp, apcu_bc, apfd, bitset, blackfire, bcompiler, blenc, bz2_filter, coin_acceptor, crack, datadog_trace, enchant, fann, gearman, geoip, gnupg, gnupg2, grpc, gupnp, hprose, igbinary, imagick, inotify, intl, jsmin, json_post, jsonc, jsond, jsonlint, kerberos, lzf, mailparse, maxminddb, mcrypt, memcache, memcached, mongodb, msgpack, mssql, mysql, mysqli, oauth, oci8, odbc, opcache, pdf, pdo_dblib, pdo_firebird, pdo_mysql, pdo_odbc, pdo_pgsql, pdo_sqlite, pgsql, phalcon, phpiredis, pinba, propro, ps, pspell, radius, rar, rdkafka, recode, redis, rrd, rrdtool, rrdtool1, rrdtool2, rrdtool3, rrdtool4, rrdtool5, rrdtool6, rrdtool7, rrd
    - uses: "ramsey/composer-install@v2"        
        
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /sharedirs/sharedir0/leonan.teixeira/public_html/
