name: 🚀 Deploy website on push
on:
  push:
    branches: [ main ]
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📚 Prepare bib file
      run: |
        npm install
        sudo apt install xsltproc libxml2-utils bibutils bibtool -y
        mkdir lattes
        cd lattes
        git clone https://github.com/urbcomp-lab/SLattes.git
        cd SLattes
        xsltproc lattes2mods.xsl ../../curriculo.xml > curriculo.mods
        xml2bib -b -w curriculo.mods > curriculo.bib
        cp publications.bib ../../publications.bib
        cd ../../
        node bibToJSON.js publications.bib > publications.json

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /sharedirs/sharedir0/leonan.teixeira/public_html/
